version: '3.8'

services:
  app:
    build:
      context: . # Build from the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: jwt_auth_app
    restart: unless-stopped
    env_file:
      - .env # Load environment variables from .env file
    ports:
      # Map host port 8080 to container port (defined by PORT env var, default 8080)
      - "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      - redis # Ensure Redis starts before the app
    networks:
      - auth_network

  redis:
    image: "redis:7-alpine" # Use a specific version
    container_name: jwt_auth_redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning # Persist data every 60s if at least 1 key changed
    # If you set a password in .env (REDIS_PASSWORD), uncomment and set it here:
    # command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data # Persist Redis data
    ports:
      # Optionally expose Redis port to host for debugging (remove in production)
      - "6379:6379"
    networks:
      - auth_network

volumes:
  redis_data: # Define the named volume for persistence

networks:
  auth_network: # Define the network
    driver: bridge